config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'

  get 'home/profile'

  root to: 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, except: [:index]

  def index
  end

  def profile
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Привет это главная страница</h1>

<% if user_signed_in? %>
	Ты можешь зайти в свой: <%= link_to 'профайл', home_profile_path %>
<% else %>
	<%= link_to 'Зарегистрироваться', new_user_registration_path %><br >
	<%= link_to 'войти', new_user_session_path %>

<% end %>

app/views/home/profile.html.erb
<h1>Это твой профайл!</h1>  

Это твой email: <strong><%= current_user.email %></strong>

Нажми <%= link_to 'выйти', destroy_user_session_path, method: :delete %>

<h3><%= link_to 'главная', root_path %></h3>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Deviseapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= notice %>
<%= alert %>

<%= yield %>

</body>
</html>